### ISSUE TITLE
Left align logo in external facing header?

### ISSUE THREAD

**Issue by andymantell** [LandRegistry/hmlr-design-system-legacy#29]
The logo in the external facing header has a gap to the left rather than being left aligned like the body content below it.

![image](https://user-images.githubusercontent.com/134642/54274915-3abbe180-4581-11e9-9de5-894ef1b225cf.png)

vs

![image](https://user-images.githubusercontent.com/134642/54274942-4909fd80-4581-11e9-9b94-f4b2e43ccd95.png)

Which is "correct" / preferable?

**Comment by joehonywill** [comment]
Left align plz.
